on: 
  schedule: 
    - cron: '0 4 * * 1'
  workflow_dispatch: 

name: 'acr/aspnet-helloworld/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          
          if [[ -z $REGION ]]; then
          export REGION=westus
          fi
          
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=csoaz-rg-$RANDOM
          echo "Using '"$RESOURCE_GROUP"' as resource group"
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          
          if [[ -z $ACR_NAME ]]; then
          export ACR_NAME=csoazacr$RANDOM
          fi
          
          az acr create \
          --name $ACR_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku Basic \
          --admin-enabled true
          
          cd acr/aspnet-helloworld
          
          dotnet publish --runtime linux-x64 -p:PublishSingleFile=true --self-contained --configuration Release
          export ACR_HELLOWORLD_IMAGE=helloworld:latest
          
          az acr build --resource-group $RESOURCE_GROUP --registry $ACR_NAME --image $ACR_HELLOWORLD_IMAGE .
          
          cd ../..
          
          
          az group delete --name $RESOURCE_GROUP --yes || true