on: 
  workflow_dispatch: 

name: 'appservice/deploy-aspnet-helloworld/README.md'
jobs: 
  validate: 
    runs-on: 'windows-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          dotnet new web --no-https --exclude-launch-settings
          dotnet publish --runtime linux-x64 --self-contained --configuration Release
          cd bin/Release/net8.0/linux-x64/publish
          zip -r deploy.zip *
          export APPSERVICE_HELLOWORLD=csoaz-asp-helloworld-$RANDOM
          
          az webapp create \
          --resource-group $RESOURCE_GROUP \
          --plan $APPSERVICE_PLAN \
          --name $APPSERVICE_HELLOWORLD \
          --runtime "DOTNETCORE:8.0"
          az webapp deploy \
          --resource-group $RESOURCE_GROUP \
          --name $APPSERVICE_HELLOWORLD \
          --src-path deploy.zip \
          --type zip