on: 
  schedule: 
    - cron: '0 1 * * 0'
  workflow_dispatch: 

name: 'gemeral/install-az-powershell-module/README.md'
jobs: 
  validate: 
    runs-on: 'windows-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force