on: 
  schedule: 
    - cron: '0 0 * * 6'
  workflow_dispatch: 

name: 'group/create/README.md'
jobs: 
  validate: 
    runs-on: 'windows-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=csoz-$RANDOM
          export REGION=northcentralus
          fi
          
          az group create --name $RESOURCE_GROUP --location $REGION
          
          export RESULT=$(az group show --name $RESOURCE_GROUP --output tsv --query properties.provisioningState)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != Succeeded ]]; then
          exit 1
          fi